version: 2
jobs:
  Ding:
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
workflows:
  version: 2
  Tada:
    jobs:
      - ding
